apiVersion: apps/v1
kind: Deployment
metadata:
  name:  webapp-deploy
  labels: 
    apps: webapp
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: webapp
    template:
      metadata:
        labels:
          app: webapp
      spec:
        containers: 
        - name: webapp
          image : 490004643334.dkr.ecr.us-west-1.amazonaws.com/node:latest
          ports: 
            containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100