apiVersion: apps/v1
kind: Deployment
metadata:
  name:  api-deploy
  labels: 
    apps: api
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: api
    template:
      metadata:
        labels:
          app: api
      spec:
        containers: 
        - name: api
          image : 490004643334.dkr.ecr.us-west-1.amazonaws.com/api
          ports: 
            containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      